logging.level.ir.mojir.keycloak_initializer=TRACE

configurationFilePath=C:\\Projects\\Estelam\\tools\\docker\\person-manager-new\\keycloak-initializer-data\\config.json
resultFilePath=C:\\Projects\\Estelam\\tools\\docker\\person-manager-new\\keycloak-initializer-data\\result.json